### ISSUE TITLE
typify-impl tests fail for Rust versions >= 1.77.1

### ISSUE THREAD

**Issue by david-r-cox** [oxidecomputer/typify#648]
```
cargo-typify> failures:
cargo-typify>
cargo-typify> ---- convert::tests::test_int_nonzerou16 stdout ----
cargo-typify> thread 'convert::tests::test_int_nonzerou16' panicked at typify-impl/src/convert.rs:1950:5:
cargo-typify> assertion `left == right` failed
cargo-typify>   left: "NonZeroU16"
cargo-typify>  right: "NonZero<u16>"
cargo-typify> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cargo-typify>
cargo-typify> ---- convert::tests::test_int_nonzerou32 stdout ----
cargo-typify> thread 'convert::tests::test_int_nonzerou32' panicked at typify-impl/src/convert.rs:1951:5:
cargo-typify> assertion `left == right` failed
cargo-typify>   left: "NonZeroU32"
cargo-typify>  right: "NonZero<u32>"
cargo-typify>
cargo-typify> ---- convert::tests::test_int_nonzerou64 stdout ----
cargo-typify> thread 'convert::tests::test_int_nonzerou64' panicked at typify-impl/src/convert.rs:1952:5:
cargo-typify> assertion `left == right` failed
cargo-typify>   left: "NonZeroU64"
cargo-typify>  right: "NonZero<u64>"
cargo-typify>
cargo-typify> ---- convert::tests::test_int_nonzerou8 stdout ----
cargo-typify> thread 'convert::tests::test_int_nonzerou8' panicked at typify-impl/src/convert.rs:1949:5:
cargo-typify> assertion `left == right` failed
cargo-typify>   left: "NonZeroU8"
cargo-typify>  right: "NonZero<u8>"
cargo-typify>
cargo-typify>
cargo-typify> failures:
cargo-typify>     convert::tests::test_int_nonzerou16
cargo-typify>     convert::tests::test_int_nonzerou32
cargo-typify>     convert::tests::test_int_nonzerou64
cargo-typify>     convert::tests::test_int_nonzerou8
cargo-typify>
cargo-typify> test result: FAILED. 98 passed; 4 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.01s
cargo-typify>
cargo-typify> error: test failed, to rerun pass `-p typify-impl --lib`
```

**Comment by ahl** [comment]
That's great! Thanks. I was looking forward to `NonZero` being stabilized!
